[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/portal/*"
  to = "/organizer.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/ops/group"
  to = "/ops-group.html"
  status = 200

[[redirects]]
  from = "/api/portal"
  to = "/.netlify/functions/portal"
  status = 200

[[redirects]]
  from = "/api/portals"
  to = "/.netlify/functions/portals"
  status = 200

[[redirects]]
  from = "/api/ops-portal"
  to = "/.netlify/functions/ops-portal"
  status = 200

[[redirects]]
  from = "/join/:code"
  to = "/.netlify/functions/join?code=:code"
  status = 200

[[redirects]]
  from = "/guest/*"
  to = "/guest.html"
  status = 200

[[redirects]]
  from = "/api/guest"
  to = "/.netlify/functions/guest"
  status = 200

[[redirects]]
  from = "/api/create-group"
  to = "/.netlify/functions/create-group"
  status = 200

[[redirects]]
  from = "/api/save-transfers"
  to = "/.netlify/functions/save-transfers"
  status = 200
